name: nginx

on:
  workflow_dispatch:

jobs:
  nginx:
    runs-on: ubuntu-latest
    env:
      DOMAIN: "<domain>"
      DEPLOY_DIR: "nic/<domain>"
      SERVER_USER: "ubuntu"
      PUBLIC_IP: "<ip>"
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_NIC_1 }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Prepare SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_ed25519
          ssh-keyscan -H $PUBLIC_IP >> ~/.ssh/known_hosts

      - name: Copy nic.conf
        run: |
          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_ed25519 -r nginx/* $SERVER_USER@$PUBLIC_IP:/home/$SERVER_USER/tmp/$DOMAIN/nginx

      - name: Run nginx.sh
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_ed25519 $SERVER_USER@$PUBLIC_IP "sudo DOMAIN=$DOMAIN DEPLOY_DIR=$DEPLOY_DIR SERVER_USER=$SERVER_USER bash /home/$SERVER_USER/tmp/$DOMAIN/sh/nginx.sh"
